language: node_js
node_js:
- stable
install:
- npm install
script:
- npm run build
# Testing & Coverage
- npm test
after_success:
- npm run coverage
deploy:
- provider: npm
  email: ''
  api_key:
  on:
    tags: true
    repo: Perryvw/TypescriptToLua
